"""
Ralph Wiggum Stop Hook — Prevents Claude from exiting until task is complete.
Intercepts exit signal and checks if task file exists in /Done/.

Usage:
  - Place in .claude/hooks/stop.py
  - Claude will call this hook before exiting
  - If task not in Done/, re-injects prompt and blocks exit
  - Max 10 iterations, then writes ALERT file
"""
import os
import sys
import logging
from pathlib import Path
from datetime import datetime, timezone

# Setup logging
logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s [RalphWiggum] %(levelname)s — %(message)s",
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler("AI_Employee_Vault/Logs/ralph_wiggum.log"),
    ],
)
logger = logging.getLogger(__name__)


def check_task_completion() -> bool:
    """
    Check if the current task has been completed.
    Task is complete if a corresponding file exists in /Done/.

    Returns:
        True if task is complete, False otherwise.
    """
    vault_path = Path(os.getenv("VAULT_PATH", "./AI_Employee_Vault"))
    done_path = vault_path / "Done"

    if not done_path.exists():
        logger.warning(f"Done path does not exist: {done_path}")
        return False

    # Check if there are any files in Done/ (task completion indicator)
    done_files = list(done_path.glob("*.md"))

    if done_files:
        logger.info(f"Task complete! Found {len(done_files)} files in Done/")
        return True

    logger.info("No files in Done/ - task not complete")
    return False


def get_ralph_counter() -> int:
    """Get current Ralph Wiggum iteration counter."""
    try:
        return int(os.getenv("RALPH_COUNTER", "0"))
    except ValueError:
        return 0


def set_ralph_counter(counter: int) -> None:
    """Set Ralph Wiggum iteration counter."""
    # Write to temp file for next iteration
    counter_file = Path("AI_Employee_Vault/Logs/ralph_counter.txt")
    counter_file.parent.mkdir(parents=True, exist_ok=True)
    counter_file.write_text(str(counter))
    logger.debug(f"Ralph counter set to: {counter}")


def write_alert(counter: int) -> None:
    """
    Write ALERT file when max iterations reached.

    Args:
        counter: Final counter value
    """
    vault_path = Path(os.getenv("VAULT_PATH", "./AI_Employee_Vault"))
    needs_action_path = vault_path / "Needs_Action"

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    alert_file = needs_action_path / f"ALERT_ralph_max_{timestamp}.md"

    content = f"""---
type: alert
from: RalphWiggum
subject: Max iterations reached without task completion
received: {datetime.now(timezone.utc).isoformat()}
priority: high
status: pending
---
## Ralph Wiggum Alert

The AI Employee agent has reached the maximum number of iterations ({counter})
without completing the task and moving files to /Done/.

## Required Actions

- [ ] Review what the agent was trying to accomplish
- [ ] Check if there are errors blocking completion
- [ ] Manually move files to /Done/ if task is actually complete
- [ ] Or provide clearer instructions to the agent

## Debug Info

- **Counter**: {counter}
- **Timestamp**: {datetime.now(timezone.utc).isoformat()}
- **Vault Path**: {vault_path}

This alert was automatically generated by the Ralph Wiggum stop hook.
"""

    alert_file.write_text(content, encoding='utf-8')
    logger.error(f"ALERT written: {alert_file}")


def main():
    """Main hook entry point."""
    logger.info("=" * 50)
    logger.info("Ralph Wiggum Stop Hook — Checking task completion")
    logger.info("=" * 50)

    # Get configuration
    max_iterations = int(os.getenv("RALPH_MAX_ITERATIONS", "10"))
    current_counter = get_ralph_counter()

    logger.info(f"Max iterations: {max_iterations}, Current: {current_counter}")

    # Check if task is complete
    if check_task_completion():
        logger.info("✓ Task complete — allowing exit")
        print("RALPH_WIGGUM: Task complete, exit allowed")
        sys.exit(0)

    # Task not complete - check iteration limit
    if current_counter >= max_iterations:
        logger.error(f"✗ Max iterations ({max_iterations}) reached")
        write_alert(current_counter)
        print(f"RALPH_WIGGUM: Max iterations ({max_iterations}) reached. ALERT written.")
        # Exit cleanly but indicate failure
        sys.exit(0)

    # Increment counter
    new_counter = current_counter + 1
    set_ralph_counter(new_counter)

    logger.warning(f"✗ Task not complete — blocking exit (iteration {new_counter}/{max_iterations})")

    # Re-inject prompt by writing to a special file
    vault_path = Path(os.getenv("VAULT_PATH", "./AI_Employee_Vault"))
    reinject_file = vault_path / "Logs" / "ralph_reinject.txt"
    reinject_file.parent.mkdir(parents=True, exist_ok=True)

    reinject_file.write_text(
        f"RALPH WIGGUM HOOK: Task not complete. "
        f"Iteration {new_counter}/{max_iterations}. "
        f"Please continue working until files are moved to /Done/."
    )

    print(f"RALPH_WIGGUM: Task not complete. Iteration {new_counter}/{max_iterations}. Re-injecting prompt.")

    # Exit with special code to signal prompt re-injection needed
    # Claude Code should catch this and re-prompt
    sys.exit(1)


if __name__ == "__main__":
    main()
