#!/usr/bin/env python3
"""
Ralph Wiggum stop-hook for Qwen Code - prevents premature exit until tasks are complete.
Max 10 iterations before escalating to human via ALERT file.
"""
import os
import sys
from datetime import datetime
from pathlib import Path


def main():
    """Implement Ralph Wiggum stop-hook logic."""
    # Get the Ralph Wiggum counter from environment (default to 0)
    ralph_counter = int(os.environ.get("RALPH_COUNTER", "0"))

    # Get the task file reference from environment
    task_file = os.environ.get("TASK_FILE", "")

    # Get the vault path
    possible_vault_paths = [
        Path("./AI_Employee_Vault"),
        Path("../AI_Employee_Vault"),
        Path("../../AI_Employee_Vault"),
        Path(os.environ.get("VAULT_PATH", "./AI_Employee_Vault"))
    ]

    vault_path = None
    for path in possible_vault_paths:
        if path.exists():
            vault_path = path
            break

    if vault_path is None:
        print("[Ralph] Vault not found - allowing exit (test mode)")
        sys.exit(0)

    done_path = vault_path / "Done"
    needs_action_path = vault_path / "Needs_Action"

    # Check if task file exists in Done/
    task_in_done = False
    if task_file:
        task_filename = Path(task_file).name
        done_task_file = done_path / task_filename
        task_in_done = done_task_file.exists()

    # Also check if ANY .md files exist in Done/ (fallback)
    if not task_in_done:
        try:
            done_files = list(done_path.glob("*.md"))
            task_in_done = len(done_files) > 0
        except Exception:
            pass

    # Ralph Wiggum logic:
    # Exit allowed : task file exists in Done/
    # Exit blocked : counter < 10 → increment, re-inject prompt, sys.exit(1)
    # Max reached  : counter == 10 → write ALERT_ralph_max_<task>.md → sys.exit(0)

    if task_in_done:
        # Exit allowed - reset counter and exit normally
        print(f"[Ralph] Task complete ✅ - allowing exit")
        os.environ["RALPH_COUNTER"] = "0"  # Reset counter
        sys.exit(0)
    else:
        # Exit blocked - check if we've reached max iterations
        if ralph_counter >= 10:
            # Max reached - write alert and exit normally
            print(f"[Ralph] Max iterations reached ⚠️ - creating alert")

            if needs_action_path.exists():
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                alert_filename = f"ALERT_ralph_max_{timestamp}.md"
                alert_file = needs_action_path / alert_filename

                alert_content = f"""---
type: alert
from: ralph_wiggum_hook
subject: Maximum Iterations Reached
received: {datetime.now().isoformat()}
priority: high
status: pending
---
# Ralph Wiggum Maximum Iterations Reached

**Timestamp:** {datetime.now().isoformat()}
**Counter:** {ralph_counter}
**Task File:** {task_file or 'Not specified'}

## What Happened

The Ralph Wiggum stop-hook has prevented exit for 10 consecutive checks.
This indicates that the autonomous AI employee may be stuck on a task
or requires manual intervention to complete the current workflow.

## Please Check

1. The `Needs_Action/` folder for unprocessed items
2. The `Pending_Approval/` folder for items awaiting review
3. The `In_Progress/claude/` folder for items being processed
4. System logs for error messages
5. Whether external services (Gmail, WhatsApp) are accessible

## To Resolve

After resolving the issue, manually move a completed task to the `Done/`
folder to allow normal processing to resume.

---
*Generated by Ralph Wiggum Stop-Hook v0.1*
"""

                try:
                    with open(alert_file, 'w', encoding='utf-8') as f:
                        f.write(alert_content)
                    print(f"[Ralph] Alert created at {alert_file}")
                except Exception as e:
                    print(f"[Ralph] Failed to create alert: {e}")

            # Reset counter and exit
            os.environ["RALPH_COUNTER"] = "0"
            sys.exit(0)
        else:
            # Counter < 10 - increment and block exit
            new_counter = ralph_counter + 1
            print(f"[Ralph] Attempt {new_counter}/10 — retrying...")
            os.environ["RALPH_COUNTER"] = str(new_counter)

            # Exit with code 1 to trigger re-run
            sys.exit(1)


if __name__ == "__main__":
    main()
