"""
Filesystem watcher for detecting new files in the inbox directory.
"""
import time
from datetime import datetime
from pathlib import Path
from typing import Optional, Dict, Any

from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

from src.watchers.base_watcher import BaseWatcher
from src.config import config

logger = logging.getLogger(__name__)


class DropFolderHandler(FileSystemEventHandler):
    """Handles file system events for the inbox directory."""

    def __init__(self, watcher_instance):
        super().__init__()
        self.watcher = watcher_instance

    def on_created(self, event):
        """Handle file creation events."""
        if not event.is_directory:
            # Wait a moment to ensure file is fully written
            time.sleep(0.5)
            self.watcher.logger.info(f"Detected new file: {event.src_path}")
            self.watcher._process_file_drop(event.src_path)


class FilesystemWatcher(BaseWatcher):
    """Watcher for the filesystem inbox directory."""

    def __init__(self, config_instance=None):
        super().__init__("FilesystemWatcher", config_instance)
        self.observer = None
        self.handler = None

    def get_interval(self) -> int:
        """Return the check interval for filesystem watching."""
        return self.config.filesystem_interval

    def check_for_updates(self) -> bool:
        """
        Check for new files in the inbox directory.
        This watcher uses event-based processing rather than polling.

        Returns:
            bool: Always returns False since processing is event-driven
        """
        # This watcher uses event-driven processing via watchdog
        # The actual processing happens in the event handler
        return False

    def start_observer(self):
        """Start the filesystem observer."""
        if self.observer is not None:
            return

        self.event_handler = DropFolderHandler(self)
        self.observer = Observer()
        self.observer.schedule(
            self.event_handler,
            str(self.config.inbox_path),
            recursive=False
        )
        self.observer.start()
        self.logger.info(f"Started filesystem watcher on {self.config.inbox_path}")

    def stop_observer(self):
        """Stop the filesystem observer."""
        if self.observer is not None:
            self.observer.stop()
            self.observer.join()
            self.observer = None
            self.logger.info("Stopped filesystem watcher")

    def _process_file_drop(self, file_path: str):
        """
        Process a dropped file by creating an action file.

        Args:
            file_path: Path to the dropped file
        """
        try:
            file_path_obj = Path(file_path)
            file_name = file_path_obj.name
            file_size = file_path_obj.stat().st_size
            modified_time = datetime.fromtimestamp(file_path_obj.stat().st_mtime)

            update_data = {
                "type": "file_drop",
                "from": "filesystem",
                "subject": f"File dropped: {file_name}",
                "received": modified_time.isoformat(),
                "priority": "medium",
                "status": "pending",
                "watcher": "FilesystemWatcher",
                "file_name": file_name,
                "file_size": str(file_size),
                "file_path": str(file_path_obj)
            }

            # Create action file
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            safe_filename = "".join(c for c in file_name if c.isalnum() or c in "._- ")[:50]
            action_filename = f"{timestamp}_file_{safe_filename}.md"

            frontmatter_data = {
                "type": update_data.get("type", "file_drop"),
                "from": update_data.get("from", ""),
                "subject": update_data.get("subject", ""),
                "received": update_data.get("received", ""),
                "priority": update_data.get("priority", "medium"),
                "status": update_data.get("status", "pending"),
                "watcher": update_data.get("watcher", "FilesystemWatcher"),
                "file_name": update_data.get("file_name", ""),
                "file_size": update_data.get("file_size", ""),
                "file_path": update_data.get("file_path", "")
            }

            content = f"""# File Detected: {update_data.get('file_name', 'Unknown')}

**Detected:** {update_data.get('received', datetime.now().isoformat())}
**File Name:** {update_data.get('file_name', 'Unknown')}
**File Size:** {update_data.get('file_size', 'Unknown')} bytes
**Source:** Filesystem drop

---

*This action file was generated by the FilesystemWatcher.*
*Please review and move to appropriate folder for processing.*
"""

            self._create_action_file(action_filename, frontmatter_data, content)
            self.logger.info(f"Created action file for dropped file: {file_name}")

        except Exception as e:
            self.logger.error(f"Failed to process dropped file {file_path}: {e}")

    def run(self) -> None:
        """
        Main watcher loop - starts the observer and waits for events.
        """
        self.logger.info(f"Starting {self.name} watcher")
        self.start_observer()
        self._last_run = datetime.now()

        try:
            while True:
                time.sleep(1)  # Just keep the thread alive
                self._run_count += 1

                # Log periodic status
                if self._run_count % 60 == 0:  # Every 60 seconds
                    self.logger.debug(f"{self.name} watcher running (loop {self._run_count})")

        except KeyboardInterrupt:
            self.logger.info(f"{self.name} watcher stopped by user")
            self.stop_observer()
        except Exception as e:
            self.logger.error(f"Error in {self.name} watcher: {e}", exc_info=True)
            self.stop_observer()
            raise