# Professional standard implementation | Global GEMINI.md
"""
BriefingGenerator — Generates weekly CEO briefings based on vault data.
Audits revenue, task completion, and identifies bottlenecks.
"""
import logging
import yaml
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Dict, List, Any, Optional

from src.config import config
from src.actions.audit_logger import audit_logger
from src.actions.audit_logic import audit_logic

logger = logging.getLogger(__name__)


class BriefingGenerator:
    """Generates the Monday Morning CEO Briefing."""

    def __init__(self, vault_path: Path):
        self.vault_path = vault_path
        self.briefings_path = vault_path / "Briefings"
        self.briefings_path.mkdir(parents=True, exist_ok=True)
        self.business_goals_path = vault_path / "Business_Goals.md"

    def _load_business_goals(self) -> Dict[str, Any]:
        """Load objectives and targets from Business_Goals.md."""
        if not self.business_goals_path.exists():
            return {"monthly_goal": 10000, "mtd_revenue": 0}
        
        try:
            content = self.business_goals_path.read_text(encoding='utf-8')
            if content.startswith("---"):
                parts = content.split("---", 2)
                if len(parts) >= 3:
                    metadata = yaml.safe_load(parts[1])
                    return metadata or {}
        except Exception as e:
            logger.warning(f"Failed to load business goals: {e}")
        
        return {}

    def generate_weekly_briefing(self) -> Path:
        """
        Generate a weekly briefing markdown file.
        
        Returns:
            Path to the generated briefing file.
        """
        today = datetime.now(timezone.utc)
        last_week = today - timedelta(days=7)
        
        # 1. Gather Data
        goals = self._load_business_goals()
        revenue_this_week = 2450.00 # Simulated for now
        mtd_revenue = goals.get('mtd_revenue', 0) + revenue_this_week
        
        tasks_completed = self._get_completed_tasks_count(last_week)
        bottlenecks = self._identify_bottlenecks(last_week)
        optimizations = self._get_cost_optimizations()
        deadlines = self._get_upcoming_deadlines()

        # 2. Format Briefing
        timestamp = today.strftime('%Y-%m-%d')
        filename = f"{timestamp}_Monday_Briefing.md"
        filepath = self.briefings_path / filename

        content = f"""---
generated: {today.isoformat()}
period: {last_week.strftime('%Y-%m-%d')} to {today.strftime('%Y-%m-%d')}
---
# Monday Morning CEO Briefing — {timestamp}

## Executive Summary
Strong week with revenue on track. One bottleneck identified in proposal delivery.

## Revenue
- **This Week**: ${revenue_this_week:,.2f}
- **MTD Total**: ${mtd_revenue:,.2f} (Target: ${goals.get('monthly_goal', 10000):,.2f})
- **Trend**: {"On Track" if mtd_revenue > 4000 else "Action Required"}

## Completed Tasks ({len(tasks_completed)})
{self._format_task_list(tasks_completed)}

## Bottlenecks
{self._format_bottlenecks(bottlenecks)}

## Proactive Suggestions

### Cost Optimization
{self._format_optimizations(optimizations)}

### Upcoming Deadlines
{self._format_deadlines(deadlines)}

---
*Generated by AI Employee v1.0 — Review at your convenience*
"""

        filepath.write_text(content, encoding='utf-8')
        logger.info(f"Generated weekly briefing: {filepath}")
        return filepath

    def _get_completed_tasks_count(self, since: datetime) -> List[Dict]:
        """Get list of tasks completed since given date."""
        done_path = self.vault_path / "Done"
        completed = []
        
        if not done_path.exists():
            return []
            
        for f in done_path.glob("*.md"):
            mtime = datetime.fromtimestamp(f.stat().st_mtime, tz=timezone.utc)
            if mtime > since:
                # Try to extract subject from frontmatter
                subject = f.name
                try:
                    content = f.read_text(encoding='utf-8')
                    if content.startswith("---"):
                        parts = content.split("---", 2)
                        metadata = yaml.safe_load(parts[1])
                        subject = metadata.get('subject', f.name)
                except:
                    pass
                    
                completed.append({
                    'name': subject,
                    'date': mtime.strftime('%Y-%m-%d %H:%M')
                })
        
        return completed

    def _identify_bottlenecks(self, since: datetime) -> List[Dict]:
        """Identify tasks that took too long or failed."""
        # Simulated logic based on teacher's example
        return [
            {'task': 'Client B Proposal', 'expected': '2 days', 'actual': '5 days', 'delay': '+3 days'}
        ]

    def _get_cost_optimizations(self) -> List[Dict]:
        """Get cost optimization suggestions from audit logic."""
        # Mock data for demonstration
        mock_tx = [{'name': 'Notion', 'amount': 15.0, 'days_since_active': 45}]
        return audit_logic.find_cost_optimizations(mock_tx)

    def _get_upcoming_deadlines(self) -> List[Dict]:
        """Get deadlines for the next 30 days."""
        return [
            {'project': 'Project Alpha final delivery', 'date': 'Jan 15', 'days': 9},
            {'project': 'Quarterly tax prep', 'date': 'Jan 31', 'days': 25}
        ]

    def _format_task_list(self, tasks: List[Dict]) -> str:
        if not tasks:
            return "- No tasks completed this week."
        return "\n".join([f"- [x] {t['name']}" for t in tasks])

    def _format_bottlenecks(self, bottlenecks: List[Dict]) -> str:
        if not bottlenecks:
            return "No significant bottlenecks identified."
        
        table = "| Task | Expected | Actual | Delay |\n|------|----------|--------|-------|\n"
        for b in bottlenecks:
            table += f"| {b['task']} | {b['expected']} | {b['actual']} | {b['delay']} |\n"
        return table

    def _format_optimizations(self, optimizations: List[Dict]) -> str:
        if not optimizations:
            return "- No optimizations identified this week."
        
        res = ""
        for opt in optimizations:
            res += f"- **{opt['tool']}**: {opt['reason']}. Cost: ${opt['cost']}/month.\n  - [ACTION] {opt['suggestion']}\n"
        return res

    def _format_deadlines(self, deadlines: List[Dict]) -> str:
        if not deadlines:
            return "- No upcoming deadlines tracked."
        return "\n".join([f"- {d['project']}: {d['date']} ({d['days']} days)" for d in deadlines])

# Global instance
def get_generator(vault_path: Path):
    return BriefingGenerator(vault_path)
