"""
Watchdog Monitor — Health checker for all AI Employee processes.
Restarts dead watchers and writes ALERT files on repeated failures.
"""
import logging
import subprocess
import time
import psutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Optional, List

from .config import Config
from .actions.audit_logger import AuditLogger

logger = logging.getLogger(__name__)


# Process definitions for PM2 monitoring
PM2_PROCESSES = [
    "orchestrator",
    "gmail_watcher",
    "whatsapp_watcher",
    "filesystem_watcher",
]


class ProcessMonitor:
    """
    Monitors PM2 processes and system health.
    Restarts failed processes and alerts on repeated failures.
    """

    def __init__(self, config: Config):
        """
        Initialize process monitor.

        Args:
            config: Config instance
        """
        self.config = config
        self.audit_logger = AuditLogger(config.logs_path)

        self._failure_counts: Dict[str, int] = {proc: 0 for proc in PM2_PROCESSES}
        self._max_failures = 5  # Alert after 5 consecutive failures

        logger.info(f"[ProcessMonitor] Initialized for {len(PM2_PROCESSES)} processes")

    def check_pm2_processes(self) -> Dict[str, str]:
        """
        Check status of all PM2-managed processes.

        Returns:
            Dictionary mapping process name to status ('online', 'stopped', 'errored')
        """
        status = {}

        try:
            # Run pm2 list
            result = subprocess.run(
                ['pm2', 'list', '--json'],
                capture_output=True,
                text=True,
                timeout=10
            )

            if result.returncode != 0:
                logger.error("Failed to get PM2 process list")
                return {proc: 'unknown' for proc in PM2_PROCESSES}

            import json
            processes = json.loads(result.stdout)

            for proc_name in PM2_PROCESSES:
                proc_status = 'stopped'

                for proc in processes:
                    if proc.get('name') == proc_name:
                        pm2_status = proc.get('pm2_env', {}).get('status', 'stopped')
                        proc_status = 'online' if pm2_status == 'online' else 'stopped'

                        # Check if errored
                        if proc.get('pm2_env', {}).get('restart_time', 0) > 10:
                            proc_status = 'errored'

                        break

                status[proc_name] = proc_status

                # Track failures
                if proc_status != 'online':
                    self._failure_counts[proc_name] += 1
                    logger.warning(f"Process {proc_name} is {proc_status} (failures: {self._failure_counts[proc_name]})")

                    if self._failure_counts[proc_name] >= self._max_failures:
                        self._write_alert(proc_name)
                else:
                    self._failure_counts[proc_name] = 0  # Reset on success

        except subprocess.TimeoutExpired:
            logger.error("PM2 status check timed out")
            status = {proc: 'unknown' for proc in PM2_PROCESSES}

        except Exception as e:
            logger.error(f"Error checking PM2 processes: {e}", exc_info=True)
            status = {proc: 'unknown' for proc in PM2_PROCESSES}

        return status

    def _write_alert(self, process_name: str) -> None:
        """
        Write ALERT file for repeatedly failing process.

        Args:
            process_name: Name of the failing process
        """
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        alert_file = self.config.needs_action_path / f"ALERT_{process_name}_repeated_failures_{timestamp}.md"

        content = f"""---
type: alert
from: WatchdogMonitor
subject: Process {process_name} has failed {self._max_failures}+ times
received: {datetime.now(timezone.utc).isoformat()}
priority: high
status: pending
---
## Watchdog Alert: Repeated Process Failures

The process **{process_name}** has failed {self._failure_counts[process_name]} consecutive times.

## Details

- **Process**: {process_name}
- **Failure Count**: {self._failure_counts[process_name]}
- **Max Allowed**: {self._max_failures}
- **Timestamp**: {datetime.now(timezone.utc).isoformat()}

## Suggested Actions

- [ ] Check PM2 logs: `pm2 logs {process_name}`
- [ ] Review error logs in `AI_Employee_Vault/Logs/pm2/{process_name}.err.log`
- [ ] Restart the process: `pm2 restart {process_name}`
- [ ] If issue persists, check code and dependencies
- [ ] Consider increasing resources or fixing bugs

## Debug Commands

```bash
pm2 status
pm2 logs {process_name} --lines 100
pm2 describe {process_name}
```

This alert was automatically generated by the Watchdog Monitor.
"""

        alert_file.write_text(content, encoding='utf-8')
        logger.error(f"ALERT written for {process_name}: {alert_file}")

        # Log to audit
        self.audit_logger.log_action(
            action_type="watchdog_alert",
            actor="watchdog_monitor",
            target=process_name,
            parameters={'failure_count': self._failure_counts[process_name]},
            result="alert_written",
            dry_run=self.config.dry_run
        )

    def restart_process(self, process_name: str) -> bool:
        """
        Attempt to restart a PM2 process.

        Args:
            process_name: Name of the process to restart

        Returns:
            True if restart successful, False otherwise
        """
        logger.info(f"Attempting to restart {process_name}...")

        try:
            result = subprocess.run(
                ['pm2', 'restart', process_name],
                capture_output=True,
                text=True,
                timeout=30
            )

            if result.returncode == 0:
                logger.info(f"Successfully restarted {process_name}")

                self.audit_logger.log_action(
                    action_type="process_restart",
                    actor="watchdog_monitor",
                    target=process_name,
                    result="success",
                    dry_run=self.config.dry_run
                )

                return True
            else:
                logger.error(f"Failed to restart {process_name}: {result.stderr}")

                self.audit_logger.log_action(
                    action_type="process_restart",
                    actor="watchdog_monitor",
                    target=process_name,
                    result="failure",
                    error=result.stderr,
                    dry_run=self.config.dry_run
                )

                return False

        except subprocess.TimeoutExpired:
            logger.error(f"Restart timed out for {process_name}")
            return False

        except Exception as e:
            logger.error(f"Error restarting {process_name}: {e}", exc_info=True)
            return False

    def get_system_health(self) -> Dict[str, any]:
        """
        Get overall system health metrics.

        Returns:
            Dictionary with CPU, memory, disk usage
        """
        try:
            return {
                'cpu_percent': psutil.cpu_percent(interval=1),
                'memory_percent': psutil.virtual_memory().percent,
                'disk_percent': psutil.disk_usage('/').percent,
                'timestamp': datetime.now(timezone.utc).isoformat()
            }
        except Exception as e:
            logger.error(f"Error getting system health: {e}")
            return {'error': str(e)}

    def run(self) -> None:
        """
        Main monitoring loop.
        Checks processes every 30 seconds.
        """
        logger.info("[WatchdogMonitor] Starting monitoring loop")

        check_interval = 30  # seconds

        while True:
            try:
                # Check all processes
                status = self.check_pm2_processes()

                # Log summary
                online_count = sum(1 for s in status.values() if s == 'online')
                logger.info(f"Process health: {online_count}/{len(status)} online")

                # Auto-restart stopped processes (but not if they've exceeded max failures)
                for proc_name, proc_status in status.items():
                    if proc_status == 'stopped' and self._failure_counts[proc_name] < self._max_failures:
                        logger.info(f"Auto-restarting {proc_name}...")
                        self.restart_process(proc_name)

                # Check system health periodically (every 5 checks)
                if hasattr(self, '_check_count'):
                    self._check_count += 1
                else:
                    self._check_count = 1

                if self._check_count % 5 == 0:
                    health = self.get_system_health()
                    logger.info(f"System health: CPU {health.get('cpu_percent', 'N/A')}%, "
                               f"Memory {health.get('memory_percent', 'N/A')}%")

            except Exception as e:
                logger.error(f"Error in monitoring loop: {e}", exc_info=True)

            time.sleep(check_interval)


def main():
    """Entry point for watchdog monitor process."""
    import sys

    # Setup logging
    logging.basicConfig(
        level=logging.DEBUG,
        format="%(asctime)s [%(name)s] %(levelname)s — %(message)s",
        handlers=[
            logging.StreamHandler(sys.stdout),
            logging.FileHandler("AI_Employee_Vault/Logs/watchdog.log"),
        ],
    )

    # Load config
    config = Config()

    if not config.validate():
        logger.error("Configuration validation failed")
        sys.exit(1)

    # Run monitor
    monitor = ProcessMonitor(config)
    monitor.run()


if __name__ == "__main__":
    main()
